package server;

import org.eclipse.californium.core.CoapResource;
import org.eclipse.californium.core.coap.CoAP;
import org.eclipse.californium.core.server.resources.CoapExchange;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.PrintWriter;

import java.sql.*;

/**
 * Created by Patrick on 8/18/2015.
 */
public class RegisterNode extends CoapResource {

    String db = "jdbc:hsqldb:hsql://localhost/wsn_db";
    Connection connection;

    int NodeID = -1;
    int NodeType = 0;
    String NodeAddress;


    public RegisterNode(String name) {
        super(name);
    }

    @Override
    public void handlePOST(CoapExchange ex) {
        ex.accept();
        String request = ex.getRequestText();
        //writeToFile(request);
        registerNode(request);
        System.out.println(NodeID);
        if(NodeID > 0)
            createNewTable(NodeID);
        ex.respond(CoAP.ResponseCode.CREATED);
    }

    private void createNewTable(int tableName){

        String sql = "CREATE TABLE "+'"'+tableName+'"'+" ("+
                        "ID int Generated By Default As Identity,\n" +
                        "\tN_ID int Not Null,\n" +
                        "\tSensor_1 int, \n" +
                        "\tSensor_2 int,\n" +
                        "\tSensor_3 varchar(255),\n" +
                        "\tSensor_4 varchar(255),\n" +
                        "\tPrimary Key (ID)"+
                    ")";

        try {
            Class.forName("org.hsqldb.jdbc.JDBCDriver" );
            connection = DriverManager.getConnection(db, "PATRICK", "TEST");
            Statement st = connection.createStatement();
            ResultSet res = st.executeQuery(sql);

            res.close();
            st.close();
            connection.close();

        } catch (Exception e){
            e.printStackTrace();
        }
    }

    private void registerNode(String info){
        try {
            Class.forName("org.hsqldb.jdbc.JDBCDriver" );
            connection = DriverManager.getConnection(db, "PATRICK", "TEST");

            parseInfo(info);
            //System.out.println(sql_query);
            Statement st = null;
            ResultSet res = null;

            st = connection.createStatement();
            res = st.executeQuery("INSERT INTO NODE_LIST (N_ID, N_Address, N_Type, N_Battery) VALUES(" + NodeID + ",'" + NodeAddress + "'," + NodeType + ",100)");

            res.close();
            st.close();
            connection.close();

        } catch (Exception e){
            e.printStackTrace();
        }
    }

    private void parseInfo(String nodeinfo){
        String[] split = nodeinfo.split(" ");
        int ID = -1;
        int type = -1;
        String address = null;
        for(int i = 0; i < split.length; i++){
            switch(split[i]){
                case "NodeID:":{
                    NodeID = Integer.parseInt(split[i+1]);
                    i++;
                    break;
                }
                case "NodeAddress:": {
                    NodeAddress = split[i+1];
                    i++;
                    break;
                }
                case "NodeType:": {
                    NodeType = Integer.parseInt(split[i+1]);
                    i++;
                    break;
                }

                default: {
                    System.out.println("Unrecognized parameter: "+split[i]);
                }
            }
        }
    }

    private void writeToFile(String info){
        try {
            PrintWriter nodelist = new PrintWriter(new BufferedWriter(new FileWriter("node_list.txt", true)));
            nodelist.println(info);
            nodelist.flush();
            nodelist.close();

        } catch (Exception e){
            System.out.println("Error writing to file:\nFull Trace:\n"+e.getStackTrace());
        }
    }
}
